apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
data:
  artifactRepository: |
    s3:
      endpoint: minio.rwx.svc:9000
      bucket: artifacts
      region: us-west-1
      insecure: true
      accessKeySecret:
        name: artifact-repository-s3
        key: accessKey
      secretKeySecret:
        name: artifact-repository-s3
        key: secretKey
      useSDKCreds: false
