{{- $fullName := .Release.Name -}}
{{- if .Values.influxdb2.ingress.enabled }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}-http
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`{{ .Values.influxdb2.ingress.hostname }}`)
    middlewares:
    - name: {{ $fullName }}-https-redirect
    services:
    - name: {{ $fullName }}
      kind: Service
      port: http
{{- end }}
---
{{- if .Values.grafana.ingress.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}-grafana-http
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`{{ .Values.grafana.ingress.hosts | first }}`)
    middlewares:
    - name: {{ $fullName }}-https-redirect
    services:
    - name: {{ $fullName }}-grafana
      kind: Service
      port: 3000
{{- end }}
