{{- if or (.Values.grafana.ingress.enabled) (.Values.influxdb2.ingress.enabled) -}}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-https-redirect
spec:
  redirectScheme:
    scheme: https
    permanent: true
{{- end }}
