apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: influxdb-auth
  namespace: influxdb2
spec:
  encryptedData:
    admin-password: AgA/3/6zJeVCDUHh4JqmJCVn7mqnHATQOJ9fdnZcwswj/W/4aX+pqiRphyh/iEf/lQoYpmROiDmtiZfsgK2W1GAgOFI68nTMtbPjgGSlmPjhxBVqW7dHpSwvYVlNoT7W8OTKGgXBfb+2q49HEZGbLi+4bJA9M51IuevNAof1WewW3OjBScD8aQheaQ4qfz6yRyy2yhNCHnWf91eHUtGbtSUDYr7HygVRse1FqEq71qjbSOiLQuvFiAXt5A2ef2pzcwhYnh8gPR4MIsYjfvTvIDmOMb0OjCF1h7k4RCZbZnR8HwFDi8vOA3VNzXR+Y5SC3x6QC6Oq0QJwv88z4q64u+8fW54cDcFZ8jozZ6QBduzG4OIk2PCFfXYJtde4UAeHRaFT4u53QyYT5iimtXX7dNWoX3YIUCXAZWqduBPrmTe7GQmO3PLbblZaj3yZA0vwNpoFRr67L2wt4gewiCiKWAcnLu3OFDNHaGwgytTn1kTwqhTtKjA3WaaFuput+FuvuL2ZaTtrRoK+VpFWgim6wmsKZCO8Hl/sDe0a06moheeCPMB2zi6ni4dHGL7iipGtuXY7WqZNzEFISNBD7LwGF1LdrV5jjMTnCRxxn9w+/zVCCMAoFCbMuowkyUUWrf9XiXPSq0gBa/nnvCBVckGq2neCV8dzucC4kYAEd0u9ai587BoOqsmnEywlBWcT/KgN2cl6My7ZwbUsCzUPBhzYIaygJf9O1wJDnzHCQVP8ax8pSKGccWQpeKmQ7YHmd3kG5oQGJ6HVV1UNz7mbxP6EhEgclQ==
    admin-token: AgCCfj/1R+tXCzH6Yl5lxJIa4qngZbGfl+ySUDIyUWC6HxXidKhiO7f9naMkfhUrT+dy7tqWrFgo98uxTgz9MMTilnDeulEGDoBQASA/LZL5E3+AiF46MhQt/ovQW82ZqccyktqIR+PcHFjDWBuVsYPHyl7xlMG8BwqhdYdOtmUObZZG9yf611M3u8MxLUK3URICNyKwerSzarSD0rPCBPIwi2zPf1vtfRYnz5vtKkE80VOsNyPhDUiMW3ODL6QEbK80fpcTqJ7bhgOdI65NrnT+rtpnMygGjYv2CUn5hU8m3D56jUFpJjRoGX9NH4kEzKo3n+JbCNtB7PGVvvhU9ARPDXB1CLrhja56mrSeb/kTe0bBB0lNwZH76enC6xSb7PSr2lKJRKLQRrXkjQzxHfgFFNz/W67MIC770a9DR8WjUAbgQicG6eFB420rgHkOso9EJWfLE6cRWSW7ILGwf0w2nw48NN9Zw2w9+1vgSIhqDoRSf+wO9jpbJRL8ZtjoNt1gYLWgfGoA2/Cw/YWzojf9rdMNXks/I8y0DxC6OR0d4D1qN3vgMlw4d/3rbYMabkYVigFOsjnOZ33lHmv67nhlBtIgPsp9UaSJ8+Dn7XZtReJO+lmr0lNZVTKdAyy4txxmqaZM6hSc+ZH76bgg0LgCZXi2mTQIQTwkPzLCQ32t13udFQ9Oc8gL4CQT46naTsKVFBbG1aKFwevrfuMuv1ueCF35mXns5dmyNbniGLT4abD4d6giyFyqt5OmOtbZ/RwSoJoQpZEXfFJz/t7is/736sc=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: influxdb-auth
      namespace: influxdb2

