apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github
spec:
  service:
    ports:
    - port: 12000
      targetPort: 12000
  github:
    meta:
      repositories:
      - owner: mkroman
        names:
        - meta
      # GitHub will send events to the following endpoint
      webhook:
        method: POST
        endpoint: /github
        port: '12000'
        url: https://events.infra.rwx.im
        events:
        - '*'
        active: true
        contentType: json
      webhookSecret:
        name: github-eventsource-webhook
        key: secret
