bases:
- github.com/argoproj/argo-events/manifests/cluster-install?ref=v1.6.3
- github.com/argoproj/argo-events/manifests/extensions/validating-webhook?ref=v1.6.3
resources:
- base/eventbus.yaml
- base/eventsource.github.yaml
- base/ingressroute.yaml
- base/sealedsecret.github-eventsource-webhook.yaml
