apiVersion: v2
name: influxdb2
description: A helm chart for influxdb v2
type: application
version: '0.1.0'
dependencies:
- name: influxdb2
  version: 2.1.2
  repository: https://helm.influxdata.com/
  condition: influxdb2.enabled
- name: grafana
  version: 8.0.2
  repository: https://grafana.github.io/helm-charts
