velero:
  snapshotsEnabled: false

  serviceAccount:
    server:
      create: false
      name: default

  credentials:
    existingSecret: velero-aws-creds

  configuration:
    backupStorageLocation:
    - name: default
      provider: aws
      bucket: rwx-cluster-backup
      config:
        region: eu-central-003
        s3Url: https://s3.eu-central-003.backblazeb2.com

    volumeSnapshotLocation:
    - name: default
      provider: aws
      bucket: rwx-cluster-backup
      config:
        region: eu-central-003
        s3Url: https://s3.eu-central-003.backblazeb2.com

  initContainers:
  # -- Enable the AWS plugin
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.9.2
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

  schedules:
    backups-4x-daily:
      schedule: '@every 6h'
      template:
        excludedResources:
        - persistentvolumes
        - persistentvolumeclaims
        - backuptargets.longhorn.io
        - backupvolumes.longhorn.io
        - backups.longhorn.io
        - nodes.longhorn.io
        - volumes.longhorn.io
        - engines.longhorn.io
        - replicas.longhorn.io
        - backingimagedatasources.longhorn.io
        - backingimagemanagers.longhorn.io
        - backingimages.longhorn.io
        - sharemanagers.longhorn.io
        - instancemanagers.longhorn.io
        - engineimages.longhorn.io
        includedNamespaces:
        - '*'
        hooks: {}
        metadata: {}
        ttl: 720h0m0s
      useOwnerReferencesInBackup: false
