apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-eventsource-webhook
  namespace: argo-events
spec:
  encryptedData:
    secret: AgAoUD4yQCRu7YrI6wUo3HUPH7rwsYpNaRcZAM3RyxVFizchvWX93IJ8rswG6Uo9mSN/ZEU60FwLUcv7neYPyWZ5K0NPXDsfr3m3DBISQIzckWt8k7InRVqttBBN+0ioHLj6jqXWzOvapus0mMQOfY2rhg8HKGxzQspa1k0nzEDsZeOB9xTH7Rpf26TMxmcIUiyrYSc20VBWjE3BTlw06YzRA3LrHA7XyO92hxfJOpDPZtYQ9TP3vJHCaWH0dAARPW0BCDTU4OWYkfE4VfHa0qd1JM0rfFsnCjGU1Pe5XbufULWJHctL/VPyeMwuq6tjsDC27vOLtZ/RDgqsVcn8ywrFBCVm3G8zjFUASrGD/ruXtTr8CnLtskj3IthIYauJO8zrbtoDDquTC4VY6r+IefskL4sKpgoncJhbWXLrhidfCJJiqjIyuq7eehRpCoIzIV4zvy8A6zlR047expODh9N1Lhs5uKnD0o4W9pjQL2LN+EDGAAs0o1touqsG2J8cxbnlTH95f4yZawSdyNW3Cr4mgahOD3/cpW4xdnuiOYc01YOjvYYkveB1kfizXO6pTFtpU4E0OYg/KqYSBIquW8XoyB4Yrew+wMgpPkK+uHuh43NDDzssHZWN+V9ZcLtwfguMp9b3/MRUlskFrVMNJ30+Ktye1hs38hZPCFR/0OvOuYrEvt4dVI1xwcx4MeFxOrHwhJ8IulXhYmSOr6diUVmAlqf49mzFZMovG7NNEDvn9rkgJSw9PjiCSLKGMx/tRgOhwoIyxQiWV1TFz6Zblidg
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-eventsource-webhook
      namespace: argo-events
    type: Opaque

