---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: meta-deployment-sensor
spec:
  dependencies:
  - name: github
    eventSourceName: github
    eventName: meta
    filters:
      data:
      - path: body.repository.full_name
        type: string
        value:
        - mkroman/meta
      - path: body.X-GitHub-Event
        type: string
        value:
        - deployment
      - path: body.action
        type: string
        value:
        - created
  triggers:
  - template:
    name: deployment-workflow
    k8s:
      operation: create
      source:
        resource:
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            generateName: deployment-
            namespace: meta
          spec:
            entrypoint: main
            arguments:
              parameters:
              - name: message
                # the value will get overridden by event payload from test-dep
                value: hello world
            templates:
            - name: main
              inputs:
                parameters:
                - name: message
              container:
                image: docker/whalesay:latest
                command: [cowsay]
                args: ["{{inputs.parameters.message}}"]
      parameters:
        - src:
            dependencyName: test-dep
            dataKey: body
          dest: spec.arguments.parameters.0.value

