apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-aws-creds
  namespace: velero
spec:
  encryptedData:
    cloud: AgB2+jWsXjjQVA3GRPj9+KwUwDgL5FyELEYcMhD4hqFHQ3g8A9iOmGpZIsP6a8cSnNRvs+WgMBBLXZG9Jv0+B/AkndJL3Ig7YQprGqAZq5FJg+WnRce3Gj64D5P18oxg/6/Np0Pd1PTJ9uzfJBAqx865o0s9cww0hRR7Dxd77+m9+1x/A2jKCHgvx5xNuJqpJ6QOjEwhKJOsYpVD7tElgWZg6M1/8vgllrtCkbk5AzH4e9tTPFvIQP2gx82KybrTwkMRv8lAM0swrSSO5DWb36O9flIvGipQLoa0UgY1Z8M7kATJ5Jo3hAQpB4Z2nZqGW3Nnf0YBuBe2i36BJeSoepYWgi23xHMrFqs7Sm460kg9/2b5J1LW3UO8P86FM8KfxasclT/P3SIpWtSvzuuxblYRXFOSp4pAZzyfPG3zMsivhpvz7Qau+zsT9K6NDTAIpCtE4rAWsBz7XBzbYqBRZHflRJlOM+2EZmiU8EwXa0urT9quWA75Y6ZXjEvoh1avo8QSYQI9+EHdpjLMIIVbfIl4lKdOy8IH8v9lCCcOfVWk/yaYRpcFlu9aUKxTAPv5G6WTzX9/Il090p9c/K/4oiXvUq0eHc1yNfPZmMmPkua/0ue+g80MKssbOdXOmNQ1aVFkBRP+gJ7ATHDVFz9C61zLzj3iNjcO28o4bsZSL3RPwel+XiijYBoyEsv/XRx7EXqgoIJ444/ob3ijPAC10hi6fPKnuXN9OpXSCdXHN0t740j2NMVhYd7Lqb0kSDs2wZd5D6VZ+Q2/NTR+Kl1V7VQ5+8n/5eLAj4HiPfBTfE8E2UWYZQqPqyvEOkWYNgtJJCl4RqDJFhiJp9kyyXi/KEg=
  template:
    metadata:
      creationTimestamp: null
      name: velero-aws-creds
      namespace: velero
    type: Opaque

